import type { Metadata } from "next";
import { siteConfig } from "@/lib/site";
import { buildMetadata } from "@/lib/seo";
import { Breadcrumbs } from "@/components/tool/breadcrumbs";

export const metadata: Metadata = buildMetadata({
  title: "Terms of Service",
  description: `Terms of Service for ${siteConfig.name}. Read the rules and guidelines for using our online tools and calculators.`,
  path: "/terms",
});

export default function TermsPage() {
  return (
    <div className="container max-w-3xl space-y-6 py-8 md:py-12">
      <Breadcrumbs
        items={[
          { name: "Home", href: "/" },
          { name: "Terms of Service", href: "/terms" },
        ]}
      />
      <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
        Terms of Service
      </h1>
      <div className="space-y-6 leading-relaxed text-muted-foreground">
        <section className="space-y-2">
          <h2 className="text-xl font-semibold text-foreground">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing and using {siteConfig.name}, you accept and agree to be 
            bound by the terms and provision of this agreement. If you do not 
            agree to abide by the above, please do not use this service.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold text-foreground">
            2. Description of Service
          </h2>
          <p>
            {siteConfig.name} provides users with access to a rich collection of 
            resources, including various calculators, formatting tools, and data 
            generators. You understand and agree that the service is provided 
            &quot;AS-IS&quot; and that {siteConfig.name} assumes no responsibility for the 
            timeliness, deletion, mis-delivery, or failure to store any user 
            communications or personalization settings.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold text-foreground">
            3. Disclaimer of Warranties
          </h2>
          <p>
            The information and calculations provided on {siteConfig.name} are 
            for general informational and educational purposes only. While we 
            strive for accuracy, we make no guarantees regarding the exactness, 
            reliability, or completeness of the results generated by our tools.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold text-foreground">
            4. Limitation of Liability
          </h2>
          <p>
            Under no circumstances shall {siteConfig.name} or its operators be 
            liable for any direct, indirect, incidental, special, or consequential 
            damages that result from the use of, or the inability to use, the 
            materials on this site, even if {siteConfig.name} has been advised 
            of the possibility of such damages.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold text-foreground">
            5. Modifications to Service
          </h2>
          <p>
            {siteConfig.name} reserves the right at any time and from time to 
            time to modify or discontinue, temporarily or permanently, the 
            Service (or any part thereof) with or without notice.
          </p>
        </section>
      </div>
    </div>
  );
}
